# Generated by Django 5.1.1 on 2024-10-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='issues',
            field=models.CharField(max_length=100),
        ),
    ]
